In [1]:
%%writefile ~/.aws/credentials
[default]
aws_access_key_id = AKIATHKZ6KRKTFYMYC47
aws_secret_access_key = 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

Overwriting /home/studio-lab-user/.aws/credentials

In [92]:
import boto3
import pandas as pd
import numpy as np
import json
import gzip
import importlib
from boto3.dynamodb.conditions import Key, Attr
from botocore.exceptions import ClientError
from boto3.dynamodb.types import Binary
from importlib import reload
from dynamodb import DynamoTable

In [2]:
# Get the service resource.
dynamodb = boto3.client('dynamodb')

In [38]:
df = pd.read_csv("music.csv")
df.drop(columns="lyrics", inplace=True)
df_c = df.sample(500)
df_c.rename(columns={"artist_name": "Artist", "track_name": "SongTitle"}, inplace=True)

In [5]:
for i in range(400):
    try:
        artist = str(df.artist_name.iloc[i])
        song_title = str(df.track_name.iloc[i])
        genre = str(df.genre.iloc[i])
        stmt = f"INSERT INTO PrometheonMusic value {{'Artist' : '{artist}', 'SongTitle' : '{song_title}', 'genre' : '{genre}'}}"    
        dynamodb.execute_statement(Statement= stmt)
    except:
        pass

In [38]:
stmt = """
SELECT * 
FROM "PrometheonMusic" 
WHERE "energy" < 0.97
"""

In [39]:
result = dynamodb.execute_statement(Statement= stmt, ReturnConsumedCapacity="TOTAL")

In [40]:
result['ConsumedCapacity']

{'TableName': 'PrometheonMusic', 'CapacityUnits': 14.5}

In [41]:
count_items = len(result['Items'])
count_items

245

In [42]:
df = pd.DataFrame(result['Items'])

In [43]:
def chang_type(elem):
    if 'N' in elem:
        try:
            return int(elem['N'])
        except:
            return float(elem['N'])
    elif 'S' in elem:
        return elem['S']

In [44]:
df.applymap(lambda x: chang_type(x))

,Unnamed: 0,night/time,sadness,danceability,topic,instrumentalness,shake the audience,obscene,world/life,violence,...,genre,music,release_date,family/spiritual,light/visual perceptions,dating,energy,len,feelings,movement/places
0,64801,0.000634,0.000634,0.756309,world/life,0.000943,0.000634,0.000634,0.499896,0.000634,...,reggae,0.000634,1987,0.000634,0.342022,0.000634,0.568555,87,0.147936,0.000634
1,62660,0.067065,0.000822,0.703238,music,0.000000,0.000822,0.000822,0.000822,0.085902,...,jazz,0.340136,2016,0.000822,0.000822,0.318537,0.859855,102,0.000822,0.000822
2,58222,0.001815,0.001815,0.718401,violence,0.000090,0.001815,0.001815,0.001815,0.335125,...,jazz,0.001815,1984,0.001815,0.001815,0.001815,0.542528,52,0.189013,0.001815
3,65387,0.001012,0.001012,0.664248,world/life,0.000022,0.040858,0.179340,0.438142,0.001012,...,reggae,0.001012,1993,0.001012,0.001012,0.080886,0.791785,78,0.001012,0.085575
4,835,0.000907,0.000907,0.358822,world/life,0.000000,0.038488,0.000907,0.406966,0.000907,...,pop,0.055061,1959,0.000907,0.000907,0.327229,0.496481,60,0.000907,0.000907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,82306,0.090927,0.001196,0.886277,obscene,0.000329,0.038148,0.371606,0.001196,0.001196,...,hip hop,0.098982,2019,0.044295,0.092473,0.001196,0.769763,83,0.001196,0.001196
241,40293,0.001754,0.131315,0.469295,romantic,0.919028,0.001754,0.001754,0.001754,0.001754,...,blues,0.001754,1958,0.001754,0.090707,0.001754,0.183158,53,0.001754,0.001754
242,41967,0.001645,0.137612,0.273259,world/life,0.000000,0.001645,0.001645,0.693486,0.001645,...,blues,0.001645,1966,0.001645,0.001645,0.001645,0.417399,34,0.001645,0.001645
243,66274,0.120448,0.077657,0.596014,world/life,0.000000,0.000741,0.000741,0.342167,0.129185,...,reggae,0.000741,1999,0.048278,0.000741,0.000741,0.802797,126,0.000741,0.000741
244,55687,0.034687,0.383203,0.498538,violence,0.936235,0.001224,0.001224,0.083724,0.480026,...,jazz,0.001224,1964,0.001224,0.001224,0.001224,0.263240,83,0.001224,0.001224

In [33]:
from decimal import Decimal

In [39]:
json_df = df_c.to_json(orient="records")
json_df = json_df.replace("\'", "´")

In [40]:
parsed = json.loads(json_df, parse_float=Decimal)

In [41]:
dynamodb = boto3.resource('dynamodb')
table = dynamodb.Table('PrometheonMusic')

In [42]:
with table.batch_writer() as writer:
    for item in parsed:
        writer.put_item(Item=item)

In [46]:
len(table.key_schema)

2

----------------------------------

In [19]:
import dynamodb
importlib.reload(dynamodb)
from dynamodb import DynamoTable

In [4]:
tb = DynamoTable()

In [64]:
try: 
    tb.create_table("data_name", "Inv_ID", "S", "Bill_ID", "S")
except:
    tb.select_table("data_name")

In [6]:
tb

- Table name: data_name_mx
- Table arn: arn:aws:dynamodb:us-east-1:221916320853:table/data_name_mx
- Table creation: 2022-06-24 16:51:28.040000+00:00
- [{'AttributeName': 'Inv_ID', 'KeyType': 'HASH'}]
- [{'AttributeName': 'Inv_ID', 'AttributeType': 'S'}]

In [104]:
s_out = """Offer for a Basic Digital Access subscription is not open to current digital news s
ubscribers. Your payment method will automatically be charged in advance the introductory 
offer rate every 4 weeks for 1 year, and after 1 year the standard rate every 4 weeks. 
Your subscription will continue until you cancel. Cancellation takes effect at the end 4
of your current billing period. The print edition of The New York Times, Games, Cooking or 
Wirecutter are not included. Taxes may apply. Offer terms are subject to change.
"""
s_out2 = """At its fifth hearing on the Capitol riot, the panel plans to show evidence about how Donald Trump tried to manipulate the Justice Department to stay in power.
The committee is presenting his actions as a critical strand in a multilayered effort by the former president to subvert the election. Watch the hearing live.
"""
s_out3 = "At itsid Watch the hearing live."

item1 = {
    "Inv_ID": "Invoice-40539",
    "Bill_ID": "Bill-235",
    "Data1": s_out,
    "Data2": s_out2
}

item3 = {
    "Inv_ID": "Invoice-40539",
    "Bill_ID": "Bill-15",
    "Data2": s_out3
}

df = pd.DataFrame([item1, item3], index=range(2))

In [97]:
import dynamodb
importlib.reload(dynamodb)
from dynamodb import DynamoTable
tb = DynamoTable()
tb.select_table("data_name")

In [105]:
tb.batch_pandas(df, compress=True)

In [106]:
tb.query_items("Invoice-40539", to_pandas=True)

,Data1,Data2,Inv_ID,Bill_ID
0,,At itsid Watch the hearing live.,Invoice-40539,Bill-122445
1,,At itsid Watch the hearing live.,Invoice-40539,Bill-15
2,"Offer for a Basic Digital Access subscription is not open to current digital news s\nubscribers. Your payment method will automatically be charged in advance the introductory \noffer rate every 4 weeks for 1 year, and after 1 year the standard rate every 4 weeks. \nYour subscription will continue until you cancel. Cancellation takes effect at the end 4\nof your current billing period. The print edition of The New York Times, Games, Cooking or \nWirecutter are not included. Taxes may apply. Offer terms are subject to change.\n","At its fifth hearing on the Capitol riot, the panel plans to show evidence about how Donald Trump tried to manipulate the Justice Department to stay in power.\nThe committee is presenting his actions as a critical strand in a multilayered effort by the former president to subvert the election. Watch the hearing live.\n",Invoice-40539,Bill-233445
3,"Offer for a Basic Digital Access subscription is not open to current digital news s\nubscribers. Your payment method will automatically be charged in advance the introductory \noffer rate every 4 weeks for 1 year, and after 1 year the standard rate every 4 weeks. \nYour subscription will continue until you cancel. Cancellation takes effect at the end 4\nof your current billing period. The print edition of The New York Times, Games, Cooking or \nWirecutter are not included. Taxes may apply. Offer terms are subject to change.\n","At its fifth hearing on the Capitol riot, the panel plans to show evidence about how Donald Trump tried to manipulate the Justice Department to stay in power.\nThe committee is presenting his actions as a critical strand in a multilayered effort by the former president to subvert the election. Watch the hearing live.\n",Invoice-40539,Bill-235