## [Amazon DynamoDB examples (link)](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/python/example_code/dynamodb)

In [1]:
%%writefile ~/.aws/credentials
[default]
aws_access_key_id = AKIATTVLL4XTPKVJIAG5
aws_secret_access_key = ITN4eCwhh7tK6Npp1tc8YAkN2kmzjeJQmuXUSiLh

Overwriting /home/studio-lab-user/.aws/credentials

In [ ]:
%%writefile ~/.aws/config

[default]
region=us-east-1

In [2]:
from decimal import Decimal
from io import BytesIO
from datetime import datetime
import ast
import json
import logging
import os
from pprint import pprint
import requests
from zipfile import ZipFile
import boto3
import pandas as pd
from boto3.dynamodb.conditions import Key, Attr
from botocore.exceptions import ClientError

In [3]:
# Get the service resource.
dynamodb = boto3.resource('dynamodb')

In [4]:
logger = logging.getLogger(__name__)

In [5]:
    def batch_pq(self, dataframe):
        duplicat = 0
        total_cap = 0
        problem_r = []
        
        for i in range(len(dataframe)):
            try:
                data = dataframe.iloc[i].to_json(force_ascii=False)
                data = data.replace("\'", "´").replace("\\/", "/")
                data_t = ast.literal_eval(data)
                stmt = f"INSERT INTO {self.table_name} value {data_t}"
                result = self.dyn_client.execute_statement(Statement= stmt, ReturnConsumedCapacity="TOTAL")
                total_cap += result['ConsumedCapacity']['CapacityUnits']
            except ClientError as err:
                if err.response['Error']['Code'] == "DuplicateItemException":
                    duplicat += 1
                else:
                    problem_r.append(dataframe.index[i])
        
        if duplicat != 0: 
            print(f"Registros duplicados: {duplicat}")
        if len(problem_r) != 0:    
            print(f"Errores: {len(problem_r)}")
            return problem_r
        return total_cap

In [6]:
class DecimalEncoder(json.JSONEncoder):
  def default(self, obj):
    if isinstance(obj, Decimal):
      return float(obj)
    return json.JSONEncoder.default(self, obj)

In [7]:
class DynamoTable:

    def __init__(self, table_name=None):
        """
        :param table_name: A DynamoDB table.
        """
        self.table_name = table_name
        self.dyn_resource = boto3.resource('dynamodb')
        self.dyn_client = boto3.client('dynamodb')
        self.__keyType = {"S": "s", "N": 0, "B": b"b"}
        if not table_name:
            self.table_name = None
        elif not self.exists(table_name):
            print("Table doesn't exist. To create use create_table() function.")
            self.table_name = None
        else:
            self.select_table(table_name)
        
    def __repr__(self):
        if self.table_name != None:
            rep = f"- Table name: {self.table_name}\
            \n- Table arn: {self.table.table_arn}\
            \n- Table creation: {self.table.creation_date_time}\
            \n- {self.table.key_schema}\
            \n- {self.table.attribute_definitions}"
        else:
            rep = "The table has not yet been selected"
        return rep
    
    def exists(self, table_name):
        """
        Determines whether a table exists. As a side effect, stores the table in
        a member variable.
        :param table_name: The name of the table to check.
        :return: True when the table exists; otherwise, False.
        """
        try:
            self.table = self.dyn_resource.Table(table_name)
            self.table.load()
            exists = True
        except ClientError as err:
            if err.response['Error']['Code'] == 'ResourceNotFoundException':
                exists = False
            else:
                logger.error(
                    "Couldn't check for existence of %s. Here's why: %s: %s",
                    table_name,
                    err.response['Error']['Code'], err.response['Error']['Message'])
                raise
        return exists
    
    def select_table(self, table_name):
        if not self.exists(table_name):
            print("Table doesn't exist. To create use create_table() function.")
            self.table_name = None
        else:
            self.table_name = table_name
            self.all_tags = self.dyn_client.get_paginator('list_tags_of_resource')
            for i in self.all_tags.paginate(ResourceArn=self.table.table_arn):
                try:
                    if i['Tags'][0]['Key'] == "backup_num":
                        count_it = i['Tags'][0]['Value']
                        self.backup_count = int(count_it)
                    else:
                        self.backup_count = 0
                except:
                    self.backup_count = 0      
            
    @property
    def item_count(self):
        """
        Count items for a table
        """
        try:
            return self.table.item_count
        except:
            return 0
    
    def create_table(self, 
                     table_name, 
                     partition_key, 
                     partition_key_type, 
                     sort_key=None, 
                     sort_key_type=None, 
                     provisioned=True, # or 'PAY_PER_REQUEST'
                     rcu=10, 
                     wcu=10
                    ):
        """
        Creates an Amazon DynamoDB table.
        :param table_name: The name of the table to create.
        :param partition_key: Primary key name.
        :param partition_key_type: Primary key type.
        :param sort_key: Sort key name.
        :param sort_key_type: Sort key type.
        :param rcu: (Read Capacity Units) Default: 10. The maximum number of strongly consistent reads 
                    consumed per second before DynamoDB returns a ThrottlingException.
        :param wcu: (WriteCapacityUnits) Default: 10. The maximum number of writes consumed per second 
                    before DynamoDB returns a ThrottlingException.
        """           
        if sort_key != None:
            key_schema = [
                        {'AttributeName': partition_key, 'KeyType': 'HASH'},  
                        {'AttributeName': sort_key, 'KeyType': 'RANGE'}]
            att_definition = [
                        {'AttributeName': partition_key, 'AttributeType': partition_key_type},
                        {'AttributeName': sort_key, 'AttributeType': sort_key_type}]
        else:
            key_schema = [{'AttributeName': partition_key, 'KeyType': 'HASH'}]
            att_definition=[{'AttributeName': partition_key, 'AttributeType': partition_key_type}]
        try:
            if provisioned:
                self.table = self.dyn_resource.create_table(
                    TableName=table_name, 
                    KeySchema = key_schema, 
                    AttributeDefinitions = att_definition,
                    ProvisionedThroughput={'ReadCapacityUnits': rcu,
                                           'WriteCapacityUnits': wcu
                                          }
                )
            else:
                self.table = self.dyn_resource.create_table(
                    TableName=table_name, 
                    KeySchema = key_schema, 
                    AttributeDefinitions = att_definition,
                    BillingMode="PAY_PER_REQUEST")
            self.table.wait_until_exists()
            self.table_name = table_name
            self.dyn_client.tag_resource(ResourceArn=self.table.table_arn, 
                           Tags=[{'Key': 'backup_num', 'Value': '0'}]
            )
        except ClientError as err:
            logger.error(
                "Couldn't create table %s. Here's why: %s: %s", table_name,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise
    
    def batch_pandas(self, dataframe):
        df_c = dataframe.copy()
        json_df = df_c.to_json(orient="records")
        parsed = json.loads(json_df, parse_float=Decimal)
        self.write_batch(parsed)
    
    def write_batch(self, items):
        """
        Fills an Amazon DynamoDB table with the specified data, using the Boto3
        Table.batch_writer() function to put the items in the table.
        Inside the context manager, Table.batch_writer builds a list of
        requests. On exiting the context manager, Table.batch_writer starts sending
        batches of write requests to Amazon DynamoDB and automatically
        handles chunking, buffering, and retrying.
        :param items: The data to put in the table. Each item must contain at least
                       the keys required by the schema that was specified when the
                       table was created.
        """
        try:
            with self.table.batch_writer() as writer:
                for item in items:
                    writer.put_item(Item=item)
        except ClientError as err:
            logger.error(
                "Couldn't load data into table %s. Here's why: %s: %s", self.table.name,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise

    def add_movie(self, title, year, plot, rating):
        """
        Adds a movie to the table.
        :param title: The title of the movie.
        :param year: The release year of the movie.
        :param plot: The plot summary of the movie.
        :param rating: The quality rating of the movie.
        """
        try:
            self.table.put_item(
                Item={
                    'year': year,
                    'title': title,
                    'info': {'plot': plot, 'rating': Decimal(str(rating))}})
        except ClientError as err:
            logger.error(
                "Couldn't add movie %s to table %s. Here's why: %s: %s",
                title, self.table.name,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise

    def get_item(self, pk_value, se_value=None):
        """
        Gets item data from the table.
        :param pk_value: Primary key value.
        :param se_value: Sort key value.
        :return: The data about the requested item.
        """
        pk_name = self.table.key_schema[0]['AttributeName']
        pk_type = self.table.attribute_definitions[0]["AttributeType"]
        act_pk_type = self.__keyType[pk_type]
        
        if len(self.table.key_schema) == 2:
            sh_name = self.table.key_schema[1]['AttributeName']
            sh_type = self.table.attribute_definitions[1]["AttributeType"]
            act_sh_type = self.__keyType[sh_type]
            
            if se_value is None:
                print(f"The sort key value cannot be empty: {sh_name}")
                return
            elif type(pk_value) != type(act_pk_type):
                print(f"The format of the main key is incorrect, it should be: {type(act_pk_type)}")
                return
            elif type(se_value) != type(act_pk_type):
                print(f"The format of the sort key is incorrect, it should be: {type(act_pk_type)}")
                return
            response = self.table.get_item(Key={pk_name: pk_value, sh_name: se_value})
        else:
            if type(pk_value) != type(act_pk_type):
                print(f"The format of the main key is incorrect, it should be: {type(act_pk_type)}")
                return
            response = self.table.get_item(Key={pk_name: pk_value})
        try:
            js_data = json.dumps(response['Item'], cls=DecimalEncoder)
            result = json.loads(js_data)
            return result
        except:
            return (None, response)

    def scan_att(self, att_name, query, to_pandas=True, consumed_capacity=False):
        response = self.table.scan(
            FilterExpression=Attr(att_name).begins_with(query),
            ReturnConsumedCapacity="TOTAL"
        )
        if consumed_capacity:
            consumed_text = f"Consumed Capacity: {response['ConsumedCapacity']['CapacityUnits']}"
            print(consumed_text)
        
        if to_pandas:
            return pd.DataFrame(response['Items'])
        else:
            return response['Items']
        
    def update_movie(self, title, year, rating, plot):
        """
        Updates rating and plot data for a movie in the table.
        :param title: The title of the movie to update.
        :param year: The release year of the movie to update.
        :param rating: The updated rating to the give the movie.
        :param plot: The updated plot summary to give the movie.
        :return: The fields that were updated, with their new values.
        """
        try:
            response = self.table.update_item(
                Key={'year': year, 'title': title},
                UpdateExpression="set info.rating=:r, info.plot=:p",
                ExpressionAttributeValues={
                    ':r': Decimal(str(rating)), ':p': plot},
                ReturnValues="UPDATED_NEW")
        except ClientError as err:
            logger.error(
                "Couldn't update movie %s in table %s. Here's why: %s: %s",
                title, self.table.name,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise
        else:
            return response['Attributes']

    def query_items(self, query, to_pandas=True, consumed_capacity=False):
        """
        Query a table items.
        :param query: The key value to query.
        :return: Items matching the search.
        """
        try:
            pk_name = self.table.key_schema[0]['AttributeName']
            response = self.table.query(KeyConditionExpression=Key(pk_name).eq(query), 
                                        ReturnConsumedCapacity="TOTAL"
            )
        except ClientError as err:
            logger.error(
                f"Couldn't query for {query}. Here's why: {err.response['Error']['Code']} \
                {err.response['Error']['Message']}")
            raise
        
        if consumed_capacity:
            consumed_text = f"Consumed Capacity: {response['ConsumedCapacity']['CapacityUnits']}"
            print(consumed_text)
        
        if len(response['Items']) == 0:
            print("No items were found matching your search query.")
            return None
        elif to_pandas:
            return pd.DataFrame(response['Items'])
        else:
            return response['Items']


    def scan_movies(self, year_range):
        """
        Scans for movies that were released in a range of years.
        Uses a projection expression to return a subset of data for each movie.
        :param year_range: The range of years to retrieve.
        :return: The list of movies released in the specified years.
        """
        movies = []
        scan_kwargs = {
            'FilterExpression': Key('year').between(year_range['first'], year_range['second']),
            'ProjectionExpression': "#yr, title, info.rating",
            'ExpressionAttributeNames': {"#yr": "year"}}
        try:
            done = False
            start_key = None
            while not done:
                if start_key:
                    scan_kwargs['ExclusiveStartKey'] = start_key
                response = self.table.scan(**scan_kwargs)
                movies.extend(response.get('Items', []))
                start_key = response.get('LastEvaluatedKey', None)
                done = start_key is None
        except ClientError as err:
            logger.error(
                "Couldn't scan for movies. Here's why: %s: %s",
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise

        return movies

    def delete_movie(self, title, year):
        """
        Deletes a movie from the table.
        :param title: The title of the movie to delete.
        :param year: The release year of the movie to delete.
        """
        try:
            self.table.delete_item(Key={'year': year, 'title': title})
        except ClientError as err:
            logger.error(
                "Couldn't delete movie %s. Here's why: %s: %s", title,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise

    def create_backup(self, name="automatic"):
        if name == "automatic":
            self.backup_count += 1
            count_b = str(self.backup_count).zfill(5)
            name = f"Backup-{count_b}"
        else:
            name = name.replace(" ", "_")
        self.dyn_client.create_backup(
            TableName=self.table_name,
            BackupName=name
        )
        self.dyn_client.tag_resource(ResourceArn=self.table.table_arn, 
                           Tags=[{'Key': 'backup_num', 
                                  'Value': str(self.backup_count)}
                            ]
        )
        
    def delete_table(self):
        """
        Deletes the table.
        """
        try:
            self.table.delete()
            self.table = None
        except ClientError as err:
            logger.error(
                "Couldn't delete table. Here's why: %s: %s",
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise

In [15]:
dt = DynamoTable("PrometheonMusic")

In [41]:
for i in dt.dyn_client.list_backups(TableName="Books")['BackupSummaries']:
    print(i['BackupName'], i['BackupCreationDateTime'], i['BackupArn'])

Backup-0001 2022-06-16 18:22:17.530000+00:00 arn:aws:dynamodb:us-east-1:125723220249:table/Books/backup/01655403737530-1b031c5d
Backup-0002 2022-06-16 18:22:36.056000+00:00 arn:aws:dynamodb:us-east-1:125723220249:table/Books/backup/01655403756056-a7ab9d90
Backup-0003 2022-06-16 18:23:23.157000+00:00 arn:aws:dynamodb:us-east-1:125723220249:table/Books/backup/01655403803157-906c91bd
Backup-0004 2022-06-16 18:23:25.307000+00:00 arn:aws:dynamodb:us-east-1:125723220249:table/Books/backup/01655403805307-d5267742
Backup-00005 2022-06-16 18:31:03.917000+00:00 arn:aws:dynamodb:us-east-1:125723220249:table/Books/backup/01655404263917-77c76324
Backup-00001 2022-06-16 19:40:24.979000+00:00 arn:aws:dynamodb:us-east-1:125723220249:table/Books/backup/01655408424979-60712fee
Backup-00002 2022-06-16 19:41:01.753000+00:00 arn:aws:dynamodb:us-east-1:125723220249:table/Books/backup/01655408461753-2156bf15

In [42]:
dt.dyn_client.restore_table_from_backup(TargetTableName="Aprivos",
                                        BackupArn="arn:aws:dynamodb:us-east-1:125723220249:table/Books/backup/01655403737530-1b031c5d")

{'TableDescription': {'AttributeDefinitions': [{'AttributeName': 'authors',
    'AttributeType': 'S'},
   {'AttributeName': 'title', 'AttributeType': 'S'}],
  'TableName': 'Aprivos',
  'KeySchema': [{'AttributeName': 'title', 'KeyType': 'HASH'},
   {'AttributeName': 'authors', 'KeyType': 'RANGE'}],
  'TableStatus': 'CREATING',
  'CreationDateTime': datetime.datetime(2022, 6, 16, 20, 6, 43, 531000, tzinfo=tzlocal()),
  'ProvisionedThroughput': {'NumberOfDecreasesToday': 0,
   'ReadCapacityUnits': 10,
   'WriteCapacityUnits': 10},
  'TableSizeBytes': 0,
  'ItemCount': 0,
  'TableArn': 'arn:aws:dynamodb:us-east-1:125723220249:table/Aprivos',
  'TableId': 'c753e49c-1d9e-410e-815c-390877bfc451',
  'BillingModeSummary': {'BillingMode': 'PROVISIONED'},
  'RestoreSummary': {'SourceBackupArn': 'arn:aws:dynamodb:us-east-1:125723220249:table/Books/backup/01655403737530-1b031c5d',
   'SourceTableArn': 'arn:aws:dynamodb:us-east-1:125723220249:table/Books',
   'RestoreDateTime': datetime.datetime(2022, 6, 16, 18, 22, 17, 530000, tzinfo=tzlocal()),
   'RestoreInProgress': True}},
 'ResponseMetadata': {'RequestId': 'KCIFLNNKRRI1UNQL94SL93CMPVVV4KQNSO5AEMVJF66Q9ASUAAJG',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'server': 'Server',
   'date': 'Thu, 16 Jun 2022 20:06:43 GMT',
   'content-type': 'application/x-amz-json-1.0',
   'content-length': '879',
   'connection': 'keep-alive',
   'x-amzn-requestid': 'KCIFLNNKRRI1UNQL94SL93CMPVVV4KQNSO5AEMVJF66Q9ASUAAJG',
   'x-amz-crc32': '1617191465'},
  'RetryAttempts': 0}}

In [16]:
dt.create_table("PrometheonMusic", "Artist", "S", "SongTitle", "S")

In [19]:
dt.select("PrometheonMusic")

In [29]:
dt.create_backup()

In [124]:
df = pd.read_csv("music.csv")
df.drop(columns="lyrics", inplace=True)
df_c = df.sample(100)
df_c.rename(columns={"artist_name": "Artist", "track_name": "SongTitle"}, inplace=True)

In [125]:
dt.batch_pandas(df_c)

In [16]:
dt.get_item("jimmy smith", "stay loose")

{'Unnamed: 0': 56053.0,
 'night/time': 0.0015948965,
 'sadness': 0.1340638164,
 'danceability': 0.4682118488,
 'topic': 'obscene',
 'instrumentalness': 7.166e-06,
 'shake the audience': 0.0345431098,
 'obscene': 0.4179397947,
 'world/life': 0.0015948964,
 'violence': 0.1536131585,
 'like/girls': 0.0015948965,
 'loudness': 0.6671281696,
 'romantic': 0.0015948964,
 'communication': 0.0015948964,
 'family/gospel': 0.0015948963,
 'age': 0.7428571429,
 'SongTitle': 'stay loose',
 'valence': 0.8753091509,
 'Artist': 'jimmy smith',
 'acousticness': 0.2198787348,
 'genre': 'jazz',
 'music': 0.0015948964,
 'release_date': 1968.0,
 'family/spiritual': 0.0015948966,
 'light/visual perceptions': 0.1138773784,
 'dating': 0.0015948964,
 'energy': 0.7107016756,
 'len': 119.0,
 'feelings': 0.0015948963,
 'movement/places': 0.0015948965}

In [13]:
dt.scan_att("genre", "rock")

,Unnamed: 0,night/time,sadness,danceability,topic,instrumentalness,shake the audience,obscene,world/life,violence,...,genre,music,release_date,family/spiritual,light/visual perceptions,dating,energy,len,feelings,movement/places
0,78617,0.1404474662,0.3752544851,0.5277807863,sadness,0.1912955466,0.003508772,0.003508772,0.0035087721,0.171972621,...,rock,0.0035087719,2009,0.1246868452,0.0035087721,0.0035087719,0.8658616766,30,0.0035087719,0.003508772
1,80666,0.0436105407,0.0025062657,0.5310300011,obscene,0.000002004,0.0516334155,0.4160356486,0.0025062658,0.0025062659,...,rock,0.0025062657,2018,0.0025062657,0.1043833654,0.0025062657,0.9359339351,30,0.0025062657,0.0025062658
2,71547,0.0022883298,0.3047940252,0.4606303477,sadness,0.0000047976,0.0022883295,0.0022883298,0.0022883297,0.0022883297,...,rock,0.0022883296,1969,0.0762356104,0.0022883296,0.0488525076,0.3823630928,27,0.0022883301,0.0022883296
3,73298,0.0040485831,0.3486105266,0.684826167,sadness,0.0006852227,0.1512248923,0.0040485833,0.0040485831,0.0040485834,...,rock,0.004048583,1979,0.0040485831,0.0040485833,0.004048583,0.39437548,18,0.004048583,0.2326362096
4,78365,0.024755516,0.0256863252,0.3371601863,violence,0.0207489879,0.0130443575,0.0186852935,0.0918009698,0.3148267668,...,rock,0.0006191951,2008,0.0006191951,0.0006191951,0.0006191951,0.8958926445,120,0.000619195,0.0006191951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,80460,0.0021929825,0.4629819136,0.5050362829,sadness,0,0.0021929825,0.0021929825,0.277295356,0.0021929826,...,rock,0.0021929825,2017,0.0021929825,0.0021929827,0.0021929825,0.723715095,29,0.0021929828,0.0021929825
37,75634,0.0013157896,0.0013157895,0.2624282465,violence,0.8633603239,0.0013157895,0.0325474349,0.1770022683,0.4196437157,...,rock,0.0013157895,1990,0.1969771414,0.0013157895,0.0013157895,0.912910193,73,0.0013157895,0.0013157895
38,70951,0.0700121244,0.4474237834,0.7454781761,sadness,0.6376518219,0.0016977929,0.0016977929,0.0016977929,0.0016977929,...,rock,0.0016977929,1964,0.0016977929,0.0016977929,0.0016977929,0.8268214182,32,0.3814968927,0.0016977931
39,72803,0.0009746589,0.0581776783,0.4433012022,violence,0,0.0009746589,0.0009746589,0.1191985146,0.5877193099,...,rock,0.000974659,1977,0.0009746589,0.0009746589,0.0009746589,0.7707636114,67,0.0009746589,0.0981006046
40,73170,0.0435202513,0.0010121458,0.7400628182,violence,0.0497975709,0.0010121459,0.1363269649,0.0010121458,0.6110329211,...,rock,0.0010121458,1979,0.0010121458,0.0010121458,0.0010121459,0.6045922555,89,0.0577296711,0.0010121458

In [44]:
dt.query_items("elvis presley", consumed_capacity=True)

Consumed Capacity: 0.5

,Unnamed: 0,night/time,sadness,danceability,topic,instrumentalness,shake the audience,obscene,world/life,violence,...,genre,music,release_date,family/spiritual,light/visual perceptions,dating,energy,len,feelings,movement/places
0,71547,0.0022883298,0.3047940252,0.4606303477,sadness,0.0000047976,0.0022883295,0.0022883298,0.0022883297,0.0022883297,...,rock,0.0022883296,1969,0.0762356104,0.0022883296,0.0488525076,0.3823630928,27,0.0022883301,0.0022883296

            None                                    {'NULL': True}
            True/False                              {'BOOL': True/False}
            int/Decimal                             {'N': str(value)}
            string                                  {'S': string}
            Binary/bytearray/bytes (py3 only)       {'B': bytes}
            set([int/Decimal])                      {'NS': [str(value)]}
            set([string])                           {'SS': [string])
            set([Binary/bytearray/bytes])           {'BS': [bytes]}
            list                                    {'L': list}
            dict                                    {'M': dict}