## [Amazon DynamoDB examples (link)](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/python/example_code/dynamodb)

In [1]:
%%writefile source.txt
[default]
aws_access_key_id = AKIAQQSPIJES4UYABDUG
aws_secret_access_key = vufJz5Q9N6gUPrvQTRfDISd4su5xZHBH7hMwR/PD

Writing source.txt

In [2]:
!mv source.txt ../.aws/credentials

In [3]:
from decimal import Decimal
from io import BytesIO
import json
import logging
import os
from pprint import pprint
import requests
from zipfile import ZipFile
import boto3
import pandas as pd
from boto3.dynamodb.conditions import Key, Attr
from botocore.exceptions import ClientError

In [4]:
# Get the service resource.
dynamodb = boto3.resource('dynamodb')

In [5]:
logger = logging.getLogger(__name__)

In [6]:
class DecimalEncoder(json.JSONEncoder):
  def default(self, obj):
    if isinstance(obj, Decimal):
      return float(obj)
    return json.JSONEncoder.default(self, obj)

In [7]:
class DynamoTable:

    def __init__(self, table_name):
        """
        :param table_name: A DynamoDB table.
        """
        self.table_name = table_name
        self.dyn_resource = boto3.resource('dynamodb')
        self.__keyType = {"S": "s", "N": 0, "B": b"b"}
        if not self.exists(table_name):
            print("Table doesn't exist. To create use create_table() function.")
            self.table_name = None
        else:
            self._item_count = self.table.item_count
        
    def __repr__(self):
        if self.table_name != None:
            rep = f"- Table name: {self.table_name}\n- {self.table.table_arn}\
            \n- {self.table.key_schema}\
            \n- {self.table.attribute_definitions}"
        else:
            rep = "The table has not yet been selected"
        return rep
    
    def exists(self, table_name):
        """
        Determines whether a table exists. As a side effect, stores the table in
        a member variable.
        :param table_name: The name of the table to check.
        :return: True when the table exists; otherwise, False.
        """
        try:
            self.table = self.dyn_resource.Table(table_name)
            self.table.load()
            exists = True
        except ClientError as err:
            if err.response['Error']['Code'] == 'ResourceNotFoundException':
                exists = False
            else:
                logger.error(
                    "Couldn't check for existence of %s. Here's why: %s: %s",
                    table_name,
                    err.response['Error']['Code'], err.response['Error']['Message'])
                raise
        return exists

    @property
    def item_count(self):
        """
        Count items for a table
        """
        try:
            print("Ok")
            return self.table.item_count
        except:
            return 0
    
    def create_table(self, table_name, partition_key, partition_key_type, sort_key=None, sort_key_type=None):
        """
        Creates an Amazon DynamoDB table.
        :param table_name: The name of the table to create.
        :param partition_key: Primary key name.
        :param sort_key: Sort key name.
        :return: The newly created table.
        """
        if sort_key != None:
            key_schema = [
                        {'AttributeName': partition_key, 'KeyType': 'HASH'},  
                        {'AttributeName': sort_key, 'KeyType': 'RANGE'}]
            att_definition = [
                        {'AttributeName': partition_key, 'AttributeType': partition_key_type},
                        {'AttributeName': sort_key, 'AttributeType': sort_key_type}]
        else:
            key_schema = [{'AttributeName': partition_key, 'KeyType': 'HASH'}]
            att_definition=[{'AttributeName': partition_key, 'AttributeType': partition_key_type}]
        try:
            self.table = self.dyn_resource.create_table(
                TableName=table_name, 
                KeySchema = key_schema, 
                AttributeDefinitions = att_definition,
                ProvisionedThroughput={'ReadCapacityUnits': 10, 'WriteCapacityUnits': 10})
            self.table.wait_until_exists()
        except ClientError as err:
            logger.error(
                "Couldn't create table %s. Here's why: %s: %s", table_name,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise
        else:
            return self.table
    
    def batch_pandas(self, dataframe):
        df_c = dataframe.astype(str)
        json_df = df_c.to_json(orient="records")
        parsed = json.loads(json_df)
        self.write_batch(parsed)
    
    def write_batch(self, items):
        """
        Fills an Amazon DynamoDB table with the specified data, using the Boto3
        Table.batch_writer() function to put the items in the table.
        Inside the context manager, Table.batch_writer builds a list of
        requests. On exiting the context manager, Table.batch_writer starts sending
        batches of write requests to Amazon DynamoDB and automatically
        handles chunking, buffering, and retrying.
        :param items: The data to put in the table. Each item must contain at least
                       the keys required by the schema that was specified when the
                       table was created.
        """
        try:
            with self.table.batch_writer() as writer:
                for item in items:
                    writer.put_item(Item=item)
        except ClientError as err:
            logger.error(
                "Couldn't load data into table %s. Here's why: %s: %s", self.table.name,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise

    def add_movie(self, title, year, plot, rating):
        """
        Adds a movie to the table.
        :param title: The title of the movie.
        :param year: The release year of the movie.
        :param plot: The plot summary of the movie.
        :param rating: The quality rating of the movie.
        """
        try:
            self.table.put_item(
                Item={
                    'year': year,
                    'title': title,
                    'info': {'plot': plot, 'rating': Decimal(str(rating))}})
        except ClientError as err:
            logger.error(
                "Couldn't add movie %s to table %s. Here's why: %s: %s",
                title, self.table.name,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise

    def get_item(self, pk_value, se_value=None):
        """
        Gets item data from the table.
        :param pk_value: Primary key value.
        :param se_value: Sort key value.
        :return: The data about the requested item.
        """
        pk_name = self.table.key_schema[0]['AttributeName']
        pk_type = self.table.attribute_definitions[0]["AttributeType"]
        act_pk_type = self.__keyType[pk_type]
        
        if len(self.table.key_schema) == 2:
            sh_name = self.table.key_schema[1]['AttributeName']
            sh_type = self.table.attribute_definitions[1]["AttributeType"]
            act_sh_type = self.__keyType[sh_type]
            
            if se_value is None:
                print(f"The sort key value cannot be empty: {sh_name}")
                return
            elif type(pk_value) != type(act_pk_type):
                print(f"The format of the main key is incorrect, it should be: {type(act_pk_type)}")
                return
            elif type(se_value) != type(act_pk_type):
                print(f"The format of the sort key is incorrect, it should be: {type(act_pk_type)}")
                return
            response = self.table.get_item(Key={pk_name: pk_value, sh_name: se_value})
        else:
            if type(pk_value) != type(act_pk_type):
                print(f"The format of the main key is incorrect, it should be: {type(act_pk_type)}")
                return
            response = self.table.get_item(Key={pk_name: pk_value})
        try:
            js_data = json.dumps(response['Item'], cls=DecimalEncoder)
            result = json.loads(js_data)
            return result
        except:
            return (None, response)

    def scan_att(self, att_name, query, to_pandas=True):
        response = self.table.scan(
            FilterExpression=Attr(att_name).begins_with(query))
        if to_pandas:
            return pd.DataFrame(response['Items'])
        else:
            return response['Items']
        
    def update_movie(self, title, year, rating, plot):
        """
        Updates rating and plot data for a movie in the table.
        :param title: The title of the movie to update.
        :param year: The release year of the movie to update.
        :param rating: The updated rating to the give the movie.
        :param plot: The updated plot summary to give the movie.
        :return: The fields that were updated, with their new values.
        """
        try:
            response = self.table.update_item(
                Key={'year': year, 'title': title},
                UpdateExpression="set info.rating=:r, info.plot=:p",
                ExpressionAttributeValues={
                    ':r': Decimal(str(rating)), ':p': plot},
                ReturnValues="UPDATED_NEW")
        except ClientError as err:
            logger.error(
                "Couldn't update movie %s in table %s. Here's why: %s: %s",
                title, self.table.name,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise
        else:
            return response['Attributes']

    def query_items(self, query, to_pandas=True):
        """
        Query a table items.
        :param query: The key value to query.
        :return: Items matching the search.
        """
        try:
            pk_name = self.table.key_schema[0]['AttributeName']
            response = self.table.query(KeyConditionExpression=Key(pk_name).eq(query))
        except ClientError as err:
            logger.error(
                "Couldn't query for movies released in %s. Here's why: %s: %s", year,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise
        else:
            if len(response['Items']) == 0:
                print("No items were found matching your search query.")
                return None
            elif to_pandas:
                return pd.DataFrame(response['Items'])
            else:
                return response['Items']


    def scan_movies(self, year_range):
        """
        Scans for movies that were released in a range of years.
        Uses a projection expression to return a subset of data for each movie.
        :param year_range: The range of years to retrieve.
        :return: The list of movies released in the specified years.
        """
        movies = []
        scan_kwargs = {
            'FilterExpression': Key('year').between(year_range['first'], year_range['second']),
            'ProjectionExpression': "#yr, title, info.rating",
            'ExpressionAttributeNames': {"#yr": "year"}}
        try:
            done = False
            start_key = None
            while not done:
                if start_key:
                    scan_kwargs['ExclusiveStartKey'] = start_key
                response = self.table.scan(**scan_kwargs)
                movies.extend(response.get('Items', []))
                start_key = response.get('LastEvaluatedKey', None)
                done = start_key is None
        except ClientError as err:
            logger.error(
                "Couldn't scan for movies. Here's why: %s: %s",
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise

        return movies

    def delete_movie(self, title, year):
        """
        Deletes a movie from the table.
        :param title: The title of the movie to delete.
        :param year: The release year of the movie to delete.
        """
        try:
            self.table.delete_item(Key={'year': year, 'title': title})
        except ClientError as err:
            logger.error(
                "Couldn't delete movie %s. Here's why: %s: %s", title,
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise

    def delete_table(self):
        """
        Deletes the table.
        """
        try:
            self.table.delete()
            self.table = None
        except ClientError as err:
            logger.error(
                "Couldn't delete table. Here's why: %s: %s",
                err.response['Error']['Code'], err.response['Error']['Message'])
            raise

In [20]:
dt.create_table("PrometheonMusic", "Artist", "S", "SongTitle", "S")

dynamodb.Table(name='PrometheonMusic')

In [21]:
dt = DynamoTable("PrometheonMusic")

In [22]:
df = pd.read_csv("music.csv")
df_c = df[["artist_name", "track_name", "music", "energy", "genre"]].sample(22).astype(str)
df_c.rename(columns={"artist_name": "Artist", "track_name": "SongTitle"}, inplace=True)

In [23]:
dt.batch_pandas(df_c)

In [30]:
dt.get_item("the who", "i'm one")

{'energy': '0.5615478681616483',
 'genre': 'rock',
 'Artist': 'the who',
 'music': '0.2406520484606962',
 'SongTitle': "i'm one"}

In [28]:
dt.scan_att("genre", "rock")

,energy,genre,Artist,music,SongTitle
0,0.8278224505109669,rock,corrosion of conformity,0.0007412898559976,stare too long
1,0.3673476088542505,rock,survivor,0.0020242915553304,ever since the world began
2,0.8498451603293317,rock,radiohead,0.0058479533887239,paranoid android
3,0.1381112202903634,rock,the kingston trio,0.0015479878231751,across the wide missouri
4,0.5615478681616483,rock,the who,0.2406520484606962,i'm one
5,0.7727656759650551,rock,the who,0.0526879894181725,you better you bet
6,0.878875095998994,rock,nirvana,0.0029239766251865,very ape
7,0.3793599960279039,rock,john mayer,0.2633845119489144,speak for me

In [31]:
dt.query_items("the who")

               energy genre   Artist               music           SongTitle
0  0.5615478681616483  rock  the who  0.2406520484606962             i'm one
1  0.7727656759650551  rock  the who  0.0526879894181725  you better you bet

            None                                    {'NULL': True}
            True/False                              {'BOOL': True/False}
            int/Decimal                             {'N': str(value)}
            string                                  {'S': string}
            Binary/bytearray/bytes (py3 only)       {'B': bytes}
            set([int/Decimal])                      {'NS': [str(value)]}
            set([string])                           {'SS': [string])
            set([Binary/bytearray/bytes])           {'BS': [bytes]}
            list                                    {'L': list}
            dict                                    {'M': dict}